import { useEffect, useState } from 'react'
import { AnimatePresence, motion, useReducedMotion } from 'framer-motion'
import { ArrowDown, ArrowRight, ArrowUpRight, ChevronLeft, ChevronRight } from 'lucide-react'
import { Link } from 'react-router-dom'
import { services } from '../../data/content'
import { industryLinks, productLinks, serviceLinks } from '../../data/sitePages'

const photo = (id, w = 1200) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=85`
const scenes = [
  { image:'photo-1558494949-ef010cbdcc31', label:'Network intelligence', text:'See the systems behind every signal.', color:'#36c8bd', to:'/products/argos-enms' },
  { image:'photo-1516321318423-f06f85e504b3', label:'Cybersecurity', text:'Make exposure easier to understand.', color:'#85d8d1', to:'/services/cybersecurity' },
  { image:'photo-1581091226825-a6a2a5aee158', label:'Connected operations', text:'Bring field data into the decisions that matter.', color:'#b7e8d9', to:'/services/iot' },
]
const storyCards = [
  { tag:'Network intelligence', title:'From infrastructure signals to operational clarity', image:'photo-1758691737124-05c5bffe46f0', to:'/products/argos-enms', n:'01' },
  { tag:'Cyber exposure', title:'Understand what is exposed. Prioritize what matters.', image:'photo-1758873269276-9518d0cb4a0b', to:'/products/panoptix', n:'02' },
  { tag:'Industrial IoT', title:'Connect physical operations with useful insight', image:'photo-1581091212991-8891c7d4bd9b', to:'/services/iot', n:'03' },
]

export default function ExperienceHome() {
  const [activeScene, setActiveScene] = useState(0)
  const [activeStory, setActiveStory] = useState(0)
  const [activeService, setActiveService] = useState(0)
  const reduceMotion = useReducedMotion()
  const scene = scenes[activeScene]
  const service = services[activeService]
  const servicePath = ['/services/cybersecurity','/services/network','/services/application','/services/iot','/services/network','/services/application','/services/iot','/services/network'][activeService]
  useEffect(() => {
    if (reduceMotion) return undefined
    const timer = window.setInterval(() => setActiveStory((current) => (current + 1) % storyCards.length), 5000)
    return () => window.clearInterval(timer)
  }, [reduceMotion])
  useEffect(() => {
    if (reduceMotion) return undefined
    const timer = window.setInterval(() => setActiveScene((current) => (current + 1) % scenes.length), 6000)
    return () => window.clearInterval(timer)
  }, [reduceMotion])
  const changeStory = (step) => setActiveStory((current) => (current + step + storyCards.length) % storyCards.length)
  const story = storyCards[activeStory]
  return <main className="experience-home overflow-hidden bg-white text-[#36444b]">
    <section className="experience-hero relative flex min-h-[760px] items-center overflow-hidden bg-[#003e49] pt-28 md:min-h-[850px]">
      <div className="absolute inset-0 overflow-hidden"><AnimatePresence initial={false}><motion.img key={scene.image} src={photo(scene.image,2000)} alt="" className="absolute inset-0 h-full w-full object-cover opacity-35" initial={reduceMotion?false:{opacity:0,scale:1.12,x:activeScene%2===0?'-1.5%':'1.5%'}} animate={{opacity:.35,scale:1.035,x:activeScene%2===0?'1%':'-1%'}} exit={{opacity:0,scale:1.08}} transition={{opacity:{duration:reduceMotion ? .01 : .8,ease:'easeInOut'},scale:{duration:reduceMotion ? .01 : 5.7,ease:'linear'},x:{duration:reduceMotion ? .01 : 5.7,ease:'linear'}}}/></AnimatePresence><div className="absolute inset-0 bg-gradient-to-r from-[#003e49] via-[#005564]/85 to-[#247b8b]/30"/><div className="absolute inset-0 bg-gradient-to-t from-[#003e49] via-transparent to-[#005564]/30"/></div>
      <div className="pointer-events-none absolute -left-32 top-16 h-[30rem] w-[30rem] rounded-full bg-[#43b4c2]/20 blur-[110px]"/>
      <motion.div className="pointer-events-none absolute -right-20 top-1/4 h-[34rem] w-[34rem] rounded-full border border-white/10" animate={reduceMotion ? {} : {rotate:360}} transition={{duration:70,repeat:Infinity,ease:'linear'}}><div className="absolute left-12 top-8 h-3 w-3 rounded-full bg-[#39c4b8] shadow-[0_0_32px_#39c4b8]"/></motion.div>
      <div className="relative z-10 mx-auto grid w-full max-w-[1440px] gap-10 px-6 pb-36 md:px-12 lg:grid-cols-[1fr_.55fr] lg:items-end lg:pb-44">
        <motion.div key={activeScene} initial={{opacity:0,y:24}} animate={{opacity:1,y:0}} transition={{duration:.65}}>
          <p className="mb-8 flex items-center gap-3 font-mono text-xs uppercase tracking-[.3em] text-[#80d8d1]"><span className="h-px w-10 bg-[#36c8bd]"/>Gyanshu Technologies <span className="text-white/40">/</span> {scene.label}</p>
          <h1 className="max-w-5xl font-display text-6xl font-medium leading-[.94] tracking-[-.055em] text-white md:text-8xl lg:text-[7.4rem]">Intelligence.<br/><span className="text-[#8edbd5]">Trust.</span> Innovation.</h1>
          <p className="mt-8 max-w-2xl text-lg leading-relaxed text-white/75 md:text-xl">Secure critical systems. Connect complex operations. Build technology that moves your organization forward.</p>
          <div className="mt-9 flex flex-wrap gap-4"><a href="#capabilities" className="inline-flex items-center gap-3 rounded-full bg-[#12a99d] px-7 py-4 text-sm font-semibold text-white transition hover:bg-[#08766e]">Explore capabilities <ArrowRight size={17}/></a><Link to="/contact" className="inline-flex items-center gap-3 rounded-full border border-white/35 px-7 py-4 text-sm font-semibold text-white transition hover:border-white hover:bg-white/10">Talk to our team <ArrowUpRight size={17}/></Link></div>
        </motion.div>
        <div className="hidden justify-self-end pb-2 lg:block"><p className="max-w-xs text-right text-lg leading-relaxed text-white/70">{scene.text}</p><p className="mt-3 text-right font-mono text-xs uppercase tracking-[.2em]" style={{color:scene.color}}>Explore the story ↗</p></div>
      </div>
      <div className="absolute inset-x-0 bottom-0 z-20 border-t border-white/15 bg-[#07191d]/55 backdrop-blur-md"><div className="mx-auto flex max-w-[1440px] flex-col justify-between gap-5 px-6 py-5 md:flex-row md:items-center md:px-12"><div className="flex flex-wrap gap-x-7 gap-y-2 font-mono text-[10px] uppercase tracking-[.18em] text-white/55 md:text-xs"><span className="text-[#9be3dd]">Explore Gyanshu</span><Link className="hover:text-white" to="/services/cybersecurity">Cybersecurity</Link><Link className="hover:text-white" to="/products/argos-enms">Network intelligence</Link><Link className="hover:text-white" to="/services/iot">IoT & smart operations</Link></div><div className="flex items-center gap-3"><span className="mr-2 font-mono text-[10px] uppercase tracking-widest text-white/40">0{activeScene+1} / 0{scenes.length}</span>{scenes.map((s,i)=><button aria-label={`Show ${s.label}`} key={s.label} onClick={()=>setActiveScene(i)} className={`h-1.5 rounded-full transition-all ${i===activeScene?'w-12 bg-[#49cfc2]':'w-5 bg-white/35 hover:bg-white/70'}`}/>)}</div></div></div>
      <a href="#stories" aria-label="Scroll to stories" className="absolute bottom-24 right-7 z-20 hidden items-center gap-3 font-mono text-[10px] uppercase tracking-widest text-white/45 md:flex">Scroll to explore <ArrowDown size={15}/></a>
    </section>

    <section id="stories" className="relative z-30 -mt-1 bg-white pb-20 pt-20 md:pb-28 md:pt-28">
      <div className="mx-auto max-w-[1440px] px-6 md:px-12"><div className="mb-12 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="mb-4 font-mono text-xs uppercase tracking-[.24em] text-[#008c83]">Featured perspectives</p><h2 className="max-w-2xl font-display text-4xl leading-tight tracking-tight md:text-6xl">Technology that makes a difference.</h2></div><p className="max-w-md text-[#718087]">Explore platforms and capabilities built for the systems people rely on every day.</p></div>
        <div className="experience-card group relative isolate min-h-[430px] overflow-hidden rounded-[1.35rem] bg-[#0b292c] md:min-h-[540px]" aria-roledescription="carousel" aria-label="Featured perspectives">
          <AnimatePresence mode="wait"><motion.div key={story.n} className="absolute inset-0" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} transition={{duration:reduceMotion ? .01 : .55,ease:'easeInOut'}}>
            <motion.img src={photo(story.image,1800)} alt="" className="absolute inset-0 h-full w-full object-cover opacity-80" initial={reduceMotion?false:{scale:1.14,x:activeStory%2===0?'-1.8%':'1.8%'}} animate={reduceMotion?{}:{scale:1.035,x:activeStory%2===0?'1.2%':'-1.2%'}} transition={{duration:4.75,ease:'linear'}}/><div className="absolute inset-0 bg-gradient-to-r from-[#07191d]/90 via-[#07191d]/48 to-transparent"/><div className="absolute inset-0 bg-gradient-to-t from-[#07191d]/60 via-transparent to-transparent"/>
            <Link to={story.to} className="absolute inset-0" aria-label={`Explore ${story.title}`} />
            <div className="experience-card-copy pointer-events-none absolute inset-y-0 left-0 flex max-w-2xl flex-col justify-end p-7 pb-24 md:p-12 md:pb-28"><span className="mb-5 inline-flex w-fit rounded-full border border-white/35 bg-[#005564]/35 px-4 py-2 font-mono text-[10px] uppercase tracking-[.2em] text-white backdrop-blur">{story.tag}</span><h3 className="font-display text-3xl leading-tight text-white md:text-5xl">{story.title}</h3><span className="mt-6 inline-flex items-center gap-2 text-sm font-semibold text-[#9be3dd]">Discover more <ArrowUpRight size={17}/></span></div>
          </motion.div></AnimatePresence>
          <div className="absolute inset-x-0 bottom-0 z-10 flex items-center justify-between border-t border-white/20 bg-[#003e49]/55 px-6 py-4 backdrop-blur-md md:px-10"><div className="flex items-center gap-3"><span className="font-mono text-xs text-white/75">0{activeStory+1}</span><div className="flex gap-2">{storyCards.map((item,i)=><button key={item.n} onClick={()=>setActiveStory(i)} aria-label={`Show featured story ${i+1}: ${item.tag}`} aria-current={activeStory===i?'true':undefined} className={`h-1.5 rounded-full transition-all duration-300 ${activeStory===i?'w-12 bg-[#54c6d3]':'w-5 bg-white/40 hover:bg-white/75'}`}/>)}</div><span className="font-mono text-xs text-white/50">0{storyCards.length}</span></div><div className="flex gap-2"><button onClick={()=>changeStory(-1)} aria-label="Previous featured story" className="rounded-full border border-white/35 p-2.5 text-white transition hover:border-[#54c6d3] hover:bg-[#54c6d3]/20"><ChevronLeft size={18}/></button><button onClick={()=>changeStory(1)} aria-label="Next featured story" className="rounded-full border border-white/35 p-2.5 text-white transition hover:border-[#54c6d3] hover:bg-[#54c6d3]/20"><ChevronRight size={18}/></button></div><div className="absolute inset-x-0 top-0 h-px bg-white/15"><motion.div key={`progress-${story.n}`} className="h-full origin-left bg-[#54c6d3] shadow-[0_0_10px_#54c6d3]" initial={{scaleX:0}} animate={{scaleX:1}} transition={{duration:reduceMotion?0:5,ease:'linear'}}/></div></div>
        </div>
      </div>
    </section>

    <section id="capabilities" className="bg-[#f2f5f4] py-20 md:py-28"><div className="mx-auto max-w-[1440px] px-6 md:px-12"><div className="grid gap-10 lg:grid-cols-[.75fr_1.25fr] lg:items-end"><div><p className="mb-4 font-mono text-xs uppercase tracking-[.24em] text-[#008c83]">Industries and services</p><h2 className="font-display text-4xl leading-tight tracking-tight md:text-6xl">Capabilities that work together.</h2></div><p className="max-w-2xl justify-self-end text-lg leading-relaxed text-[#718087]">Cybersecurity, infrastructure, software, AI, and connected operations—brought together around your environment and priorities.</p></div>
      <div className="mt-12 grid overflow-hidden rounded-[1.5rem] bg-white shadow-[0_22px_80px_rgba(15,45,49,.08)] lg:min-h-[510px] lg:grid-cols-[.78fr_1.22fr]"><div className="flex flex-col border-b border-[#dce5e3] p-5 md:p-8 lg:border-b-0 lg:border-r">{services.slice(0,6).map((item,i)=><button key={item.id} onClick={()=>setActiveService(i)} className={`group flex w-full items-center gap-4 border-b border-[#e5ebea] px-2 py-4 text-left transition ${i===activeService?'text-[#005564]':'text-[#849095] hover:text-[#36444b]'}`}><span className="font-mono text-[10px] text-[#a7a9ac]">0{i+1}</span><span className="flex-1 font-display text-lg md:text-xl">{item.title}</span><ArrowUpRight size={16} className={`transition-transform ${i===activeService?'translate-x-0 text-[#00a99d]':'-translate-x-2 opacity-0 group-hover:translate-x-0 group-hover:opacity-100'}`}/></button>)}<Link to="/solutions" className="mt-auto inline-flex items-center gap-2 px-2 pt-7 text-sm font-semibold text-[#005564]">View all capabilities <ArrowRight size={16}/></Link></div>
        <motion.div key={service.id} initial={{opacity:0}} animate={{opacity:1}} transition={{duration:.35}} className="relative flex min-h-[400px] flex-col justify-end overflow-hidden p-8 md:p-12 lg:min-h-[510px]"><img src={photo(scenes[activeService%3].image,1200)} alt="" className="absolute inset-0 h-full w-full object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-[#061719] via-[#061719]/55 to-[#061719]/10"/><div className="absolute right-8 top-8 flex h-32 w-32 items-center justify-center rounded-full border border-white/30 md:right-12 md:top-12 md:h-44 md:w-44"><div className="absolute inset-3 rounded-full border border-dashed border-white/30 animate-[spin_36s_linear_infinite]"/><span className="font-display text-3xl text-white/80">0{activeService+1}</span></div><div className="relative max-w-xl"><p className="font-mono text-xs uppercase tracking-[.2em] text-[#9be3dd]">Capability spotlight</p><h3 className="mt-4 font-display text-4xl leading-tight text-white md:text-5xl">{service.title}</h3><p className="mt-4 max-w-lg leading-relaxed text-white/75">{service.desc}</p><Link to={servicePath} className="mt-7 inline-flex items-center gap-3 rounded-full border border-white/45 px-5 py-3 text-sm font-semibold text-white transition hover:bg-white hover:text-[#005564]">Explore this capability <ArrowRight size={16}/></Link></div></motion.div>
      </div></div></section>

    <section className="overflow-hidden bg-[#09292d] py-20 text-white md:py-28"><div className="mx-auto max-w-[1440px] px-6 md:px-12"><div className="flex flex-col justify-between gap-7 md:flex-row md:items-end"><div><p className="mb-4 font-mono text-xs uppercase tracking-[.24em] text-[#72d4cc]">Built for critical operations</p><h2 className="max-w-3xl font-display text-4xl leading-tight tracking-tight text-white md:text-6xl">Purpose-built platforms.<br/>Operationally ready.</h2></div><div className="flex gap-2"><button aria-label="Scroll products left" onClick={()=>document.getElementById('product-rail')?.scrollBy({left:-380,behavior:'smooth'})} className="rounded-full border border-white/30 p-3 text-white transition hover:bg-white/10"><ChevronLeft size={19}/></button><button aria-label="Scroll products right" onClick={()=>document.getElementById('product-rail')?.scrollBy({left:380,behavior:'smooth'})} className="rounded-full border border-white/30 p-3 text-white transition hover:bg-white/10"><ChevronRight size={19}/></button></div></div>
      <div id="product-rail" className="mt-12 flex snap-x snap-mandatory gap-5 overflow-x-auto pb-6">{productLinks.map((p,i)=><Link key={p.to} to={p.to} className="experience-card group relative flex min-h-[340px] min-w-[280px] snap-start flex-1 flex-col justify-between overflow-hidden rounded-2xl border border-white/15 bg-white/[.04] p-7 transition hover:border-[#58d0c6] hover:bg-white/[.08] md:min-w-[320px]"><div className="absolute -right-14 -top-14 h-48 w-48 rounded-full border border-[#57bfb6]/20 transition duration-700 group-hover:scale-125"/><div className="relative flex items-center justify-between"><span className="font-mono text-xs text-[#76d7cf]">0{i+1} / PLATFORM</span><ArrowUpRight size={18} className="text-white/55 transition group-hover:-translate-y-1 group-hover:translate-x-1 group-hover:text-[#8be0d8]"/></div><div className="relative"><h3 className="font-display text-2xl text-white md:text-3xl">{p.label}</h3><p className="mt-3 text-sm leading-relaxed text-white/60">Technology for secure, visible, and dependable operations.</p><div className="mt-7 h-px w-full bg-white/15"><div className="h-px w-1/4 bg-[#4dc9bf] transition-all duration-500 group-hover:w-full"/></div></div></Link>)}</div>
      <Link to="/products" className="mt-5 inline-flex items-center gap-2 text-sm font-semibold text-[#9be3dd]">Explore all products <ArrowRight size={16}/></Link>
    </div></section>

    <section className="bg-white py-20 md:py-28"><div className="mx-auto max-w-[1440px] px-6 md:px-12"><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr] lg:items-end"><div><p className="mb-4 font-mono text-xs uppercase tracking-[.24em] text-[#008c83]">Operating environments</p><h2 className="font-display text-4xl leading-tight tracking-tight md:text-6xl">Every context has its own priorities.</h2></div><p className="max-w-xl text-lg leading-relaxed text-[#718087]">We shape technology around the realities of each environment—from public services and critical networks to connected facilities.</p></div><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{industryLinks.slice(0,6).map((item,i)=><Link key={item.to} to={item.to} className="experience-link-card group flex min-h-48 flex-col justify-between border-t border-[#cdd8d6] py-5 transition hover:border-[#008c83]"><div className="flex items-center justify-between"><span className="font-mono text-xs text-[#a7a9ac]">0{i+1} / CONTEXT</span><ArrowUpRight size={17} className="text-[#008c83] transition group-hover:-translate-y-1 group-hover:translate-x-1"/></div><div><h3 className="font-display text-2xl text-[#36444b]">{item.label}</h3><p className="mt-2 max-w-sm text-sm leading-relaxed text-[#7b878b]">Security, resilience, and operational insight shaped for your sector.</p></div></Link>)}</div><Link to="/industries" className="mt-8 inline-flex items-center gap-2 rounded-full border border-[#005564]/25 px-5 py-3 text-sm font-semibold text-[#005564] hover:bg-[#eff6f5]">Explore industry contexts <ArrowRight size={16}/></Link></div></section>

    <section className="relative isolate overflow-hidden bg-[#e9f3f1] py-20 md:py-28"><div className="pointer-events-none absolute -right-20 top-0 -z-10 h-[32rem] w-[32rem] rounded-full border border-[#005564]/10"/><div className="pointer-events-none absolute -right-4 top-16 -z-10 h-[24rem] w-[24rem] rounded-full border border-[#005564]/10"/><div className="mx-auto grid max-w-[1440px] gap-12 px-6 md:px-12 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div><p className="mb-4 font-mono text-xs uppercase tracking-[.24em] text-[#008c83]">How we work</p><h2 className="font-display text-4xl leading-tight tracking-tight md:text-6xl">From understanding to improvement.</h2><p className="mt-6 max-w-lg leading-relaxed text-[#718087]">A considered engineering sequence keeps priorities visible, decisions grounded, and ownership clear throughout delivery.</p><Link to="/about" className="mt-7 inline-flex items-center gap-2 text-sm font-semibold text-[#005564]">How Gyanshu works <ArrowRight size={16}/></Link></div><div className="grid gap-3 sm:grid-cols-5">{[['01','Assess'],['02','Design'],['03','Implement'],['04','Validate'],['05','Improve']].map(([n,t],i)=><motion.div key={n} initial={{opacity:0,y:20}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:i*.08}} className={`rounded-xl p-5 ${i===2?'bg-[#005564] text-white':'bg-white text-[#36444b]'}`}><span className={`font-mono text-xs ${i===2?'text-[#85dbd3]':'text-[#008c83]'}`}>{n}</span><h3 className="mt-8 font-display text-xl">{t}</h3><div className={`mt-5 h-px ${i===2?'bg-white/35':'bg-[#005564]/15'}`}><div className="h-px w-1/2 bg-[#34bcb2]"/></div></motion.div>)}</div></div></section>

    <section className="bg-white py-20 md:py-28"><div className="mx-auto max-w-[1440px] px-6 md:px-12"><div className="mb-12 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="mb-4 font-mono text-xs uppercase tracking-[.24em] text-[#008c83]">Technology in action</p><h2 className="font-display text-4xl leading-tight tracking-tight md:text-6xl">A closer look at what’s possible.</h2></div><Link to="/our-work" className="inline-flex items-center gap-2 text-sm font-semibold text-[#005564]">Explore our work <ArrowRight size={16}/></Link></div><div className="grid gap-5 lg:grid-cols-3">{[['Infrastructure intelligence','Understand network relationships, performance, and operational change.','photo-1518770660439-4636190af475'],['Security exposure management','Connect assets, vulnerabilities, and response priorities.','photo-1563013544-824ae1b704d3'],['Connected operations','Bring sensor data from edge environments into useful action.','photo-1581092160562-40aa08e78837']].map(([t,d,img],i)=><article key={t} className="experience-card group relative min-h-[410px] overflow-hidden rounded-2xl bg-[#0a2528]"><img src={photo(img,900)} alt="" loading="lazy" className="absolute inset-0 h-full w-full object-cover opacity-55 transition duration-700 group-hover:scale-105 group-hover:opacity-70"/><div className="absolute inset-0 bg-gradient-to-t from-[#07191d] via-[#07191d]/35 to-transparent"/><div className="absolute bottom-0 p-7 md:p-8"><p className="font-mono text-xs uppercase tracking-widest text-[#8cddd6]">Illustrative use case / 0{i+1}</p><h3 className="mt-4 font-display text-2xl text-white">{t}</h3><p className="mt-3 max-w-sm text-sm leading-relaxed text-white/70">{d}</p></div></article>)}</div></div></section>

    <section className="relative overflow-hidden bg-[#005564] py-20 text-white md:py-28"><div className="absolute -right-20 -top-40 h-[38rem] w-[38rem] rounded-full border border-white/10"/><div className="absolute -right-4 -top-24 h-[26rem] w-[26rem] rounded-full border border-white/10"/><div className="relative mx-auto flex max-w-[1440px] flex-col justify-between gap-10 px-6 md:flex-row md:items-end md:px-12"><div><p className="mb-5 font-mono text-xs uppercase tracking-[.24em] text-[#a5e6df]">Start a conversation</p><h2 className="max-w-4xl font-display text-5xl leading-[.98] tracking-tight text-white md:text-7xl">Let’s build what<br/>comes next.</h2><p className="mt-6 max-w-xl text-lg leading-relaxed text-white/75">Bring us your cybersecurity, infrastructure, software, AI, or IoT requirement.</p></div><Link to="/contact" className="group inline-flex shrink-0 items-center gap-4 rounded-full bg-white px-7 py-4 text-sm font-semibold text-[#005564] transition hover:bg-[#d8f3ef]">Talk to Gyanshu <span className="transition group-hover:translate-x-1"><ArrowRight size={17}/></span></Link></div></section>
  </main>
}
