import { useEffect, useMemo, useState } from 'react'
import { ArrowRight, ArrowUpRight, Check, ChevronRight, Search } from 'lucide-react'
import { Link } from 'react-router-dom'
import { AnimatePresence, motion, useReducedMotion } from 'framer-motion'
import { getPage, productLinks } from '../../data/sitePages'

const categories = ['All platforms','Network intelligence','Cybersecurity','Campus & learning']
const profiles = {
  ipdr: {category:'Network intelligence',descriptor:'IP & subscriber correlation',summary:'Turn high-volume network records into searchable traffic intelligence for investigation and operational analysis.', images:['photo-1518770660439-4636190af475','photo-1519389950473-47ba0277781c','photo-1544197150-b99a580bb7a8','photo-1558494949-ef010cbdcc31'], flow:['Ingest records','Normalize sessions','Correlate subscribers','Investigate activity'], use:['Telecom operators','Service providers','Public safety teams'], accent:'#137b82'},
  'argos-enms': {category:'Network intelligence',descriptor:'Network operations visibility',summary:'Bring network monitoring, topology, performance, and service operations into a clearer view.', images:['photo-1531297484001-80022131f5a1','photo-1544197150-b99a580bb7a8','photo-1518770660439-4636190af475','photo-1558494949-ef010cbdcc31'], flow:['Discover devices','Map topology','Monitor performance','Coordinate response'], use:['Enterprise IT','Data centres','Distributed networks'], accent:'#005564'},
  panoptix: {category:'Cybersecurity',descriptor:'External attack surface visibility',summary:'Discover internet-facing assets and changing exposure, then help teams prioritize remediation with useful context.', images:['photo-1563013544-824ae1b704d3','photo-1550751827-4bd374c3f58b','photo-1563986768609-322da13575f3','photo-1516321318423-f06f85e504b3'], flow:['Discover assets','Enrich context','Prioritize exposure','Track change'], use:['Security teams','Managed security','Digital businesses'], accent:'#0a7772'},
  vapt: {category:'Cybersecurity',descriptor:'Vulnerability assessment',summary:'Run repeatable assessments and bring findings, risk scoring, and reporting into one remediation cycle.', images:['photo-1550751827-4bd374c3f58b','photo-1563986768609-322da13575f3','photo-1563013544-824ae1b704d3','photo-1498050108023-c5249f4df085'], flow:['Define scope','Assess systems','Review findings','Track remediation'], use:['Security teams','Compliance owners','IT operations'], accent:'#475b87'},
  hms: {category:'Campus & learning',descriptor:'Hostel administration',summary:'Coordinate residential operations across room allocation, attendance, billing, visitors, and communication.', images:['photo-1529390079861-591de354faf5','photo-1523240795612-9a054b0db644','photo-1529156069898-49953e39b3ac','photo-1521737711867-e3b97375f902'], flow:['Onboard residents','Allocate rooms','Manage operations','Connect families'], use:['Hostels','Residential campuses','Student housing'], accent:'#367c73'},
  lms: {category:'Campus & learning',descriptor:'Learning management',summary:'Deliver structured learning with flexible content, assessments, progress tracking, and certification workflows.', images:['photo-1427504494785-3a9ca7044f45','photo-1509062522246-3755977927d7','photo-1523240795612-9a054b0db644','photo-1516321318423-f06f85e504b3'], flow:['Create courses','Deliver learning','Assess progress','Improve outcomes'], use:['Schools and colleges','Training teams','Corporate learning'], accent:'#87754a'},
}
const photo = (id, w=1000) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=85`
const idFor = (path) => path.split('/').pop()

const visualLabels = {
  ipdr: ['Telecom network infrastructure','Operations team collaboration','Network equipment in service'],
  'argos-enms': ['Network operations','Connected infrastructure','Data centre systems'],
  panoptix: ['Security teams at work','Cybersecurity monitoring','Digital protection'],
  vapt: ['Security assessment','Technical review','Remediation planning'],
  hms: ['Campus community','Student life','Shared campus spaces'],
  lms: ['Classroom learning','Students working together','Learning in practice'],
}

function ProductImageSequence({ id, images, accent, label }) {
  const [active, setActive] = useState(0)
  const reduceMotion = useReducedMotion()
  useEffect(() => {
    if (reduceMotion || images.length < 2) return undefined
    const timer = window.setInterval(() => setActive((current) => (current + 1) % images.length), 4800)
    return () => window.clearInterval(timer)
  }, [images, reduceMotion])
  return <div className="relative h-[300px] overflow-hidden rounded-2xl border border-white/15 bg-[#071a1d] shadow-xl md:h-[390px]" role="img" aria-label={`${label} image sequence`}>
    <AnimatePresence initial={false}><motion.img key={images[active]} src={photo(images[active],1500)} alt="" className="absolute inset-0 h-full w-full object-cover" initial={{opacity:0,scale:1.08}} animate={{opacity:1,scale:reduceMotion?1:1.035}} exit={{opacity:0}} transition={{opacity:{duration:.9},scale:{duration:4.7,ease:'linear'}}}/></AnimatePresence>
    <div className="absolute inset-0 bg-gradient-to-t from-[#071a1d]/85 via-[#071a1d]/15 to-[#071a1d]/25"/>
    <div className="absolute inset-x-0 bottom-0 flex items-end justify-between gap-4 p-5 md:p-7"><div><span className="font-mono text-[9px] uppercase tracking-[.2em] text-white/65">{label}</span><p className="mt-2 font-display text-lg text-white">{visualLabels[id]?.[active % 3] || 'People and systems in context'}</p></div><div className="flex gap-1.5">{images.map((image,index)=><button key={image} aria-label={`Show image ${index+1}`} aria-current={active===index?'true':undefined} onClick={()=>setActive(index)} className={`h-1.5 rounded-full transition-all ${index===active?'w-8':'w-2 bg-white/55'}`} style={index===active?{background:accent}:undefined}/>)}</div></div>
  </div>
}

function ProductCard({item,index}) {
  const id=idFor(item.to), profile=profiles[id], page=getPage(item.to)
  return <Link to={item.to} className="product-card group relative overflow-hidden rounded-2xl border border-[#dce6e4] bg-white transition duration-300 hover:-translate-y-1 hover:border-[#39aabd] hover:shadow-[0_18px_60px_rgba(0,85,100,.18)]">
    <div className="relative h-52 overflow-hidden bg-[#0b2528]"><img src={photo(profile.images[0],900)} alt="" loading="lazy" className="h-full w-full object-cover opacity-80 transition duration-700 group-hover:scale-105"/><div className="absolute inset-0 bg-gradient-to-t from-[#071a1d]/70 via-transparent to-[#071a1d]/15"/><span className="absolute left-5 top-5 rounded-full bg-white/90 px-3 py-1 font-mono text-[9px] uppercase tracking-widest" style={{color:profile.accent}}>{profile.category}</span><span className="absolute right-5 top-5 font-mono text-xs text-white/75">0{index+1}</span></div>
    <div className="p-6 md:p-7"><p className="font-mono text-[10px] uppercase tracking-[.18em] text-[#008c83]">{profile.descriptor}</p><h3 className="mt-3 font-display text-2xl text-[#36444b]">{page.title}</h3><p className="mt-3 min-h-[72px] text-sm leading-relaxed text-[#748187]">{profile.summary}</p><span className="mt-6 inline-flex items-center gap-2 text-sm font-semibold text-[#005564]">Explore product <ArrowRight size={16} className="transition group-hover:translate-x-1"/></span></div>
  </Link>
}

export function ProductCatalog({page}) {
  const [category,setCategory]=useState('All platforms')
  const [query,setQuery]=useState('')
  const filtered=useMemo(()=>productLinks.filter((p)=>{
    const id=idFor(p.to), profile=profiles[id], title=getPage(p.to).title.toLowerCase()
    return (category==='All platforms'||profile.category===category) && (!query||title.includes(query.toLowerCase())||profile.summary.toLowerCase().includes(query.toLowerCase()))
  }),[category,query])
  return <main className="product-experience min-h-screen bg-white text-[#36444b]">
    <section className="relative overflow-hidden bg-gradient-to-br from-[#e3f3f5] via-[#f1f8f7] to-[#d9eff0] pb-16 pt-36 md:pb-24 md:pt-48"><div className="absolute -right-40 -top-36 h-[40rem] w-[40rem] rounded-full border border-[#005564]/10"/><div className="absolute -left-24 bottom-0 h-72 w-72 rounded-full bg-[#55b9c7]/15 blur-3xl"/><div className="relative mx-auto grid max-w-7xl gap-10 px-6 md:px-12 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div><p className="mb-5 font-mono text-xs uppercase tracking-[.23em] text-[#005564]">Gyanshu / Products</p><h1 className="font-display text-5xl leading-[.98] tracking-tight md:text-7xl">Platforms built around the signal.</h1><p className="mt-7 max-w-xl text-lg leading-relaxed text-[#718087]">Purpose-built tools for network intelligence, cyber exposure, vulnerability management, and connected campus operations.</p><a href="#catalog" className="mt-8 inline-flex items-center gap-3 rounded-full bg-[#005564] px-6 py-3.5 text-sm font-semibold text-white transition hover:bg-[#003e49] hover:shadow-[0_10px_28px_rgba(0,85,100,.25)]">Browse platforms <ArrowRight size={16}/></a></div><ProductImageSequence id="catalog" images={productLinks.flatMap((item)=>profiles[idFor(item.to)].images.slice(0,1))} accent="#00a99d" label="Gyanshu product platforms"/></div></section>
    <section className="border-b border-[#dce5e3] bg-white"><div className="mx-auto flex max-w-7xl flex-wrap gap-x-9 gap-y-4 px-6 py-7 md:px-12">{categories.slice(1).map((c,i)=><button key={c} onClick={()=>{setCategory(c);document.getElementById('catalog')?.scrollIntoView({behavior:'smooth'})}} className="group flex items-center gap-3 text-left"><span className="font-mono text-[10px] text-[#a7a9ac]">0{i+1}</span><span className="font-display text-base transition group-hover:text-[#008c83] md:text-lg">{c}</span><ChevronRight size={14} className="text-[#00a99d]"/></button>)}</div></section>
    <section id="catalog" className="mx-auto max-w-7xl px-6 py-16 md:px-12 md:py-24"><div className="flex flex-col justify-between gap-7 md:flex-row md:items-end"><div><p className="font-mono text-xs uppercase tracking-[.22em] text-[#008c83]">Product portfolio</p><h2 className="mt-3 font-display text-4xl md:text-5xl">Find the right platform.</h2></div><label className="flex w-full items-center gap-3 rounded-full border border-[#cbd9d7] px-5 py-3 md:max-w-sm"><Search size={17} className="text-[#718087]"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search products" className="w-full bg-transparent text-sm outline-none placeholder:text-[#9aa4a7]"/></label></div>
      <div className="mt-8 flex flex-wrap gap-2">{categories.map(c=><button key={c} onClick={()=>setCategory(c)} className={`rounded-full border px-4 py-2 text-xs transition ${category===c?'border-[#005564] bg-[#005564] text-white':'border-[#cbd9d7] text-[#68777d] hover:border-[#005564]'}`}>{c}</button>)}</div>
      <div className="mt-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{filtered.map((item,i)=><ProductCard key={item.to} item={item} index={i}/>)}</div>
      {filtered.length===0&&<p className="py-20 text-center text-[#718087]">No products match that search. Try another name or category.</p>}
    </section>
    <section className="bg-[#09292d] py-16 text-white md:py-20"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-7 px-6 md:flex-row md:items-center md:px-12"><div><p className="font-mono text-xs uppercase tracking-[.2em] text-[#8ce2d8]">Need help choosing?</p><h2 className="mt-3 font-display text-3xl text-white md:text-4xl">Let’s map your operational needs.</h2><p className="mt-3 max-w-xl text-white/70">Talk with Gyanshu about your environment, integrations, and deployment requirements.</p></div><Link to="/contact" className="inline-flex shrink-0 items-center gap-3 rounded-full bg-white px-6 py-3.5 text-sm font-semibold text-[#005564]">Talk to our team <ArrowRight size={16}/></Link></div></section>
  </main>
}

export function ProductDetail({page}) {
  const id=idFor(page.path), profile=profiles[id]
  const related=productLinks.filter(p=>p.to!==page.path && (profiles[idFor(p.to)].category===profile.category || profile.category==='Network intelligence')).slice(0,3)
  return <main className="product-experience product-detail min-h-screen overflow-hidden bg-white text-[#36444b]">
    <section className="relative overflow-hidden bg-[#071a1d] pb-16 pt-36 text-white md:pb-24 md:pt-48"><div className="absolute inset-0 bg-[radial-gradient(ellipse_at_80%_20%,rgba(0,85,100,.42),transparent_55%)]"/><div className="relative mx-auto grid max-w-7xl items-center gap-10 px-6 md:px-12 lg:grid-cols-[1fr_.9fr]"><motion.div initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{duration:.6}}><div className="mb-8 flex items-center gap-2 font-mono text-[10px] uppercase tracking-[.2em] text-white/60"><Link to="/products" className="hover:text-white">Products</Link><ChevronRight size={12}/><span style={{color:profile.accent}}>{profile.category}</span></div><p className="font-mono text-xs uppercase tracking-[.22em]" style={{color:profile.accent}}>Gyanshu platform / {profile.descriptor}</p><h1 className="mt-5 max-w-2xl font-display text-5xl leading-[.98] tracking-tight text-white md:text-7xl">{page.title}</h1><p className="mt-6 max-w-xl font-display text-2xl leading-snug text-white/80">{page.subtitle}</p><p className="mt-4 max-w-xl leading-relaxed text-white/65">{profile.summary}</p><div className="mt-8 flex flex-wrap gap-3"><Link to="/contact" className="inline-flex items-center gap-2 rounded-full px-6 py-3.5 text-sm font-semibold text-white" style={{background:profile.accent}}>Discuss this platform <ArrowRight size={16}/></Link><a href="#capabilities" className="rounded-full border border-white/35 px-5 py-3.5 text-sm text-white hover:bg-white/10">Explore capabilities</a></div></motion.div><div className="relative"><ProductImageSequence id={id} images={profile.images} accent={profile.accent} label={profile.descriptor}/><div className="absolute -bottom-4 left-8 right-8 z-20 grid grid-cols-2 gap-2 md:left-12 md:right-12">{page.features.slice(0,2).map((f,i)=><div key={f} className="rounded-lg border border-white/15 bg-[#071a1d]/85 p-3 backdrop-blur"><span className="font-mono text-[9px] uppercase tracking-widest text-white/50">Platform focus 0{i+1}</span><p className="mt-1 text-xs font-semibold text-white">{f}</p></div>)}</div></div></div></section>
    <nav className="sticky top-0 z-30 border-b border-[#dce5e3] bg-white/95 backdrop-blur"><div className="mx-auto flex max-w-7xl gap-7 overflow-x-auto px-6 py-4 font-mono text-[10px] uppercase tracking-widest text-[#718087] md:px-12"><a href="#overview" className="shrink-0 hover:text-[#005564]">Overview</a><a href="#capabilities" className="shrink-0 hover:text-[#005564]">Capabilities</a><a href="#workflow" className="shrink-0 hover:text-[#005564]">Workflow</a><a href="#deployment" className="shrink-0 hover:text-[#005564]">Deployment</a><a href="#related" className="shrink-0 hover:text-[#005564]">Related platforms</a></div></nav>
    <section id="overview" className="mx-auto grid max-w-7xl gap-10 px-6 py-16 md:px-12 md:py-24 lg:grid-cols-[.75fr_1.25fr]"><div><p className="font-mono text-xs uppercase tracking-[.2em]" style={{color:profile.accent}}>Product overview</p><h2 className="mt-4 font-display text-4xl leading-tight md:text-5xl">Designed for clearer operational decisions.</h2></div><div><p className="text-lg leading-relaxed text-[#627278]">{page.intro}</p><div className="mt-8 grid gap-3 sm:grid-cols-2">{profile.use.map((x,i)=><div key={x} className="flex items-center gap-3 border-b border-[#dce5e3] py-4"><span className="font-mono text-xs" style={{color:profile.accent}}>0{i+1}</span><span className="text-sm font-medium">{x}</span></div>)}</div></div></section>
    <section className="bg-white py-12 md:py-16"><div className="mx-auto max-w-7xl px-6 md:px-12"><div className="mb-7 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="font-mono text-xs uppercase tracking-[.2em]" style={{color:profile.accent}}>People and systems</p><h2 className="mt-3 font-display text-3xl md:text-4xl">{profile.category} in the real world.</h2></div><p className="max-w-lg text-sm leading-relaxed text-[#718087]">A closer look at the environments and teams connected to {profile.descriptor.toLowerCase()}.</p></div><div className="grid gap-4 sm:grid-cols-3">{profile.images.slice(1,4).map((image,i)=><figure key={image} className="group relative aspect-[4/3] overflow-hidden rounded-xl bg-[#e8efee]"><img src={photo(image,800)} alt={visualLabels[id]?.[i] || profile.category} loading="lazy" className="h-full w-full object-cover transition duration-700 group-hover:scale-105"/><div className="absolute inset-0 bg-gradient-to-t from-[#071a1d]/75 via-transparent to-transparent"/><figcaption className="absolute bottom-0 p-5 font-display text-lg text-white">{visualLabels[id]?.[i] || profile.category}</figcaption></figure>)}</div></div></section>
    <section id="capabilities" className="bg-[#f3f7f6] py-16 md:py-24"><div className="mx-auto max-w-7xl px-6 md:px-12"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="font-mono text-xs uppercase tracking-[.2em]" style={{color:profile.accent}}>Core capabilities</p><h2 className="mt-3 font-display text-4xl md:text-5xl">{page.title} capabilities</h2></div><p className="max-w-md text-[#718087]">A set of connected capabilities designed to work as one practical platform.</p></div><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{page.features.map((f,i)=><motion.article key={f} initial={{opacity:0,y:18}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:i*.05,duration:.4}} className="group min-h-52 rounded-xl border border-[#dce5e3] bg-white p-6 transition hover:-translate-y-1 hover:shadow-lg"><div className="flex items-center justify-between"><span className="font-mono text-xs" style={{color:profile.accent}}>0{i+1}</span><ArrowUpRight size={17} className="text-[#a7a9ac] transition group-hover:-translate-y-1 group-hover:translate-x-1"/></div><h3 className="mt-10 font-display text-xl">{f}</h3><div className="mt-4 h-px w-10 transition-all group-hover:w-full" style={{background:profile.accent}}/></motion.article>)}</div></div></section>
    <section id="workflow" className="overflow-hidden bg-white py-16 md:py-24"><div className="mx-auto max-w-7xl px-6 md:px-12"><div className="grid gap-8 lg:grid-cols-[.8fr_1.2fr] lg:items-end"><div><p className="font-mono text-xs uppercase tracking-[.2em]" style={{color:profile.accent}}>How it works</p><h2 className="mt-3 font-display text-4xl md:text-5xl">A workflow teams can follow.</h2></div><p className="max-w-xl leading-relaxed text-[#718087]">The platform connects a sequence of practical steps, giving teams context for what happens next and why it matters.</p></div><div className="relative mt-12 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{profile.flow.map((step,i)=><motion.div key={step} initial={{opacity:0,y:18}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:i*.1}} className="relative rounded-xl p-6" style={{background:i===profile.flow.length-1?profile.accent:'#f2f6f5',color:i===profile.flow.length-1?'white':'#36444b'}}><span className="font-mono text-xs" style={{color:i===profile.flow.length-1?'#b5eee7':profile.accent}}>STEP 0{i+1}</span><h3 className="mt-8 font-display text-xl">{step}</h3>{i<profile.flow.length-1&&<ArrowRight className="absolute -right-3 top-1/2 z-10 hidden -translate-y-1/2 text-[#9aa9a7] lg:block" size={18}/>}</motion.div>)}</div></div></section>
    <section id="deployment" className="bg-[#09292d] py-16 text-white md:py-20"><div className="mx-auto grid max-w-7xl gap-10 px-6 md:px-12 lg:grid-cols-[1fr_.9fr] lg:items-center"><div><p className="font-mono text-xs uppercase tracking-[.2em] text-[#8ce2d8]">Deployment and integration</p><h2 className="mt-4 font-display text-4xl leading-tight text-white md:text-5xl">Fit the platform to your environment.</h2><p className="mt-5 max-w-xl leading-relaxed text-white/70">Deployment approach, data sources, integrations, and operational responsibilities are planned with your team to match security and service requirements.</p><Link to="/contact" className="mt-7 inline-flex items-center gap-2 rounded-full bg-white px-5 py-3 text-sm font-semibold text-[#005564]">Discuss deployment <ArrowRight size={16}/></Link></div><div className="grid gap-3 sm:grid-cols-2">{['Environment and access planning','Data-source and integration mapping','Rollout and knowledge transfer','Ongoing operational support'].map((item,i)=><div key={item} className="flex gap-3 rounded-xl border border-white/15 bg-white/[.04] p-5"><Check size={17} style={{color:profile.accent}} className="shrink-0"/><p className="text-sm leading-relaxed text-white/80">{item}</p></div>)}</div></div></section>
    <section id="related" className="mx-auto max-w-7xl px-6 py-16 md:px-12 md:py-24"><div className="flex items-end justify-between gap-6"><div><p className="font-mono text-xs uppercase tracking-[.2em] text-[#008c83]">Continue exploring</p><h2 className="mt-3 font-display text-4xl md:text-5xl">Related platforms</h2></div><Link to="/products" className="hidden items-center gap-2 text-sm font-semibold text-[#005564] sm:inline-flex">All products <ArrowRight size={16}/></Link></div><div className="mt-8 grid gap-4 md:grid-cols-3">{related.map((p,i)=><ProductCard key={p.to} item={p} index={i}/>)}</div></section>
    <section className="bg-[#005564] py-14 text-white"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-6 px-6 md:flex-row md:items-center md:px-12"><div><p className="font-mono text-xs uppercase tracking-[.2em] text-[#a5e6df]">Next step</p><h2 className="mt-2 font-display text-3xl text-white md:text-4xl">See how this can fit your environment.</h2></div><Link to="/contact" className="inline-flex shrink-0 items-center gap-2 rounded-full bg-white px-6 py-3 text-sm font-semibold text-[#005564]">Talk to Gyanshu <ArrowRight size={16}/></Link></div></section>
  </main>
}
